package entities;
// Generated Jun 16, 2019 10:41:42 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Khachhang generated by hbm2java
 */
@Entity
@Table(name = "khachhang", catalog = "qlnhasach")
public class Khachhang implements java.io.Serializable {

	private Integer id;
	private String hoTen;
	private String diaChi;
	private Integer soDienThoai;
	private String email;
	private Long tienNo;

	public Khachhang() {
	}

	public Khachhang(String hoTen, String diaChi, Integer soDienThoai, String email, Long tienNo) {
		this.hoTen = hoTen;
		this.diaChi = diaChi;
		this.soDienThoai = soDienThoai;
		this.email = email;
		this.tienNo = tienNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "hoTen", length = 50)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Column(name = "diaChi", length = 300)
	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "soDienThoai")
	public Integer getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(Integer soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "tienNo", precision = 10, scale = 0)
	public Long getTienNo() {
		return this.tienNo;
	}

	public void setTienNo(Long tienNo) {
		this.tienNo = tienNo;
	}

}
