package entities;
// Generated Jun 16, 2019 10:41:42 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Quydinh generated by hbm2java
 */
@Entity
@Table(name = "quydinh", catalog = "qlnhasach")
public class Quydinh implements java.io.Serializable {

	private int id;
	private String tenQuyDinh;
	private Integer noiDung;
	private Integer hieuLuc;

	public Quydinh() {
	}

	public Quydinh(int id) {
		this.id = id;
	}

	public Quydinh(int id, String tenQuyDinh, Integer noiDung, Integer hieuLuc) {
		this.id = id;
		this.tenQuyDinh = tenQuyDinh;
		this.noiDung = noiDung;
		this.hieuLuc = hieuLuc;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "tenQuyDinh", length = 100)
	public String getTenQuyDinh() {
		return this.tenQuyDinh;
	}

	public void setTenQuyDinh(String tenQuyDinh) {
		this.tenQuyDinh = tenQuyDinh;
	}

	@Column(name = "noiDung")
	public Integer getNoiDung() {
		return this.noiDung;
	}

	public void setNoiDung(Integer noiDung) {
		this.noiDung = noiDung;
	}

	@Column(name = "hieuLuc")
	public Integer getHieuLuc() {
		return this.hieuLuc;
	}

	public void setHieuLuc(Integer hieuLuc) {
		this.hieuLuc = hieuLuc;
	}

}
