package entities;
// Generated Jun 16, 2019 10:41:42 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Thanhtoan generated by hbm2java
 */
@Entity
@Table(name = "thanhtoan", catalog = "qlnhasach")
public class Thanhtoan implements java.io.Serializable {

	private Integer id;
	private String maHoaDon;
	private int maKhachHang;
	private String ngayThanhToan;
	private Integer tienTra;
	private Integer tienNo;

	public Thanhtoan() {
	}

	public Thanhtoan(String maHoaDon, int maKhachHang, String ngayThanhToan) {
		this.maHoaDon = maHoaDon;
		this.maKhachHang = maKhachHang;
		this.ngayThanhToan = ngayThanhToan;
	}

	public Thanhtoan(String maHoaDon, int maKhachHang, String ngayThanhToan, Integer tienTra, Integer tienNo) {
		this.maHoaDon = maHoaDon;
		this.maKhachHang = maKhachHang;
		this.ngayThanhToan = ngayThanhToan;
		this.tienTra = tienTra;
		this.tienNo = tienNo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "maHoaDon", nullable = false, length = 30)
	public String getMaHoaDon() {
		return this.maHoaDon;
	}

	public void setMaHoaDon(String maHoaDon) {
		this.maHoaDon = maHoaDon;
	}

	@Column(name = "maKhachHang", nullable = false)
	public int getMaKhachHang() {
		return this.maKhachHang;
	}

	public void setMaKhachHang(int maKhachHang) {
		this.maKhachHang = maKhachHang;
	}

	@Column(name = "ngayThanhToan", nullable = false, length = 30)
	public String getNgayThanhToan() {
		return this.ngayThanhToan;
	}

	public void setNgayThanhToan(String ngayThanhToan) {
		this.ngayThanhToan = ngayThanhToan;
	}

	@Column(name = "tienTra")
	public Integer getTienTra() {
		return this.tienTra;
	}

	public void setTienTra(Integer tienTra) {
		this.tienTra = tienTra;
	}

	@Column(name = "tienNo")
	public Integer getTienNo() {
		return this.tienNo;
	}

	public void setTienNo(Integer tienNo) {
		this.tienNo = tienNo;
	}

}
