package entities;
// Generated May 2, 2019 2:17:24 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Thutien generated by hbm2java
 */
@Entity
@Table(name = "thutien", catalog = "qlnhasach")
public class Thutien implements java.io.Serializable {

	private Integer id;
	private String maHoaDon;
	private Long tienMua;
	private Long tienThu;
	private Long noCu;
	private String ngayThu;

	public Thutien() {
	}

	public Thutien(String maHoaDon, Long tienMua, Long tienThu, Long noCu, String ngayThu) {
		this.maHoaDon = maHoaDon;
		this.tienMua = tienMua;
		this.tienThu = tienThu;
		this.noCu = noCu;
		this.ngayThu = ngayThu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "maHoaDon", length = 30)
	public String getMaHoaDon() {
		return this.maHoaDon;
	}

	public void setMaHoaDon(String maHoaDon) {
		this.maHoaDon = maHoaDon;
	}

	@Column(name = "tienMua", precision = 11, scale = 0)
	public Long getTienMua() {
		return this.tienMua;
	}

	public void setTienMua(Long tienMua) {
		this.tienMua = tienMua;
	}

	@Column(name = "tienThu", precision = 11, scale = 0)
	public Long getTienThu() {
		return this.tienThu;
	}

	public void setTienThu(Long tienThu) {
		this.tienThu = tienThu;
	}

	@Column(name = "noCu", precision = 11, scale = 0)
	public Long getNoCu() {
		return this.noCu;
	}

	public void setNoCu(Long noCu) {
		this.noCu = noCu;
	}

	@Column(name = "ngayThu", length = 50)
	public String getNgayThu() {
		return this.ngayThu;
	}

	public void setNgayThu(String ngayThu) {
		this.ngayThu = ngayThu;
	}

}
