package model;
// Generated Mar 31, 2019 3:24:52 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Loainguoidung generated by hbm2java
 */
@Entity
@Table(name = "loainguoidung", catalog = "da_java")
public class Loainguoidung implements java.io.Serializable {

	private Integer id;
	private String tenLoaiNguoiDung;

	public Loainguoidung() {
	}

	public Loainguoidung(String tenLoaiNguoiDung) {
		this.tenLoaiNguoiDung = tenLoaiNguoiDung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tenLoaiNguoiDung", length = 50)
	public String getTenLoaiNguoiDung() {
		return this.tenLoaiNguoiDung;
	}

	public void setTenLoaiNguoiDung(String tenLoaiNguoiDung) {
		this.tenLoaiNguoiDung = tenLoaiNguoiDung;
	}

}
