package model;
// Generated Mar 31, 2019 3:24:52 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sach generated by hbm2java
 */
@Entity
@Table(name = "sach", catalog = "da_java")
public class Sach implements java.io.Serializable {

	private Integer id;
	private String tenSach;
	private Integer theLoai;
	private String tacGia;
	private Long donGia;
	private Integer soLuong;

	public Sach() {
	}

	public Sach(String tenSach, Integer theLoai, String tacGia, Long donGia, Integer soLuong) {
		this.tenSach = tenSach;
		this.theLoai = theLoai;
		this.tacGia = tacGia;
		this.donGia = donGia;
		this.soLuong = soLuong;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tenSach", length = 100)
	public String getTenSach() {
		return this.tenSach;
	}

	public void setTenSach(String tenSach) {
		this.tenSach = tenSach;
	}

	@Column(name = "theLoai")
	public Integer getTheLoai() {
		return this.theLoai;
	}

	public void setTheLoai(Integer theLoai) {
		this.theLoai = theLoai;
	}

	@Column(name = "tacGia", length = 50)
	public String getTacGia() {
		return this.tacGia;
	}

	public void setTacGia(String tacGia) {
		this.tacGia = tacGia;
	}

	@Column(name = "donGia", precision = 11, scale = 0)
	public Long getDonGia() {
		return this.donGia;
	}

	public void setDonGia(Long donGia) {
		this.donGia = donGia;
	}

	@Column(name = "soLuong")
	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

}
