package model;
// Generated Mar 31, 2019 3:24:52 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", catalog = "da_java")
public class Taikhoan implements java.io.Serializable {

	private Integer id;
	private String tenDangNhap;
	private String matKhau;
	private Integer loaiNguoiDung;

	public Taikhoan() {
	}

	public Taikhoan(String tenDangNhap, String matKhau, Integer loaiNguoiDung) {
		this.tenDangNhap = tenDangNhap;
		this.matKhau = matKhau;
		this.loaiNguoiDung = loaiNguoiDung;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tenDangNhap", length = 30)
	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	@Column(name = "matKhau", length = 32)
	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	@Column(name = "loaiNguoiDung")
	public Integer getLoaiNguoiDung() {
		return this.loaiNguoiDung;
	}

	public void setLoaiNguoiDung(Integer loaiNguoiDung) {
		this.loaiNguoiDung = loaiNguoiDung;
	}

}
